# Generated by Django 3.2.8 on 2022-03-11 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventname', models.CharField(max_length=50, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('status', models.IntegerField(null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('idcard', models.CharField(max_length=50)),
                ('birth', models.DateTimeField(null=True)),
                ('sex', models.IntegerField()),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotrodangkyktx.room')),
            ],
        ),
    ]
